# ddc.vim遅延読み込み用のdein.toml

# Shougo/ddc.vim
#
#     https://github.com/Shougo/ddc.vim
#
# ddc.vimとBuiltin LSPでサブ武器を錬成した
#
#     https://riq0h.jp/2021/09/15/084023/

# vim:set fileencoding=utf-8 fileformat=unix foldmethod=marker:
