# 遅延読み込み用のdein.toml

# ddc.vim {{{
# https://github.com/Shougo/ddc.vim
[[plugins]]
repo     = 'Shougo/ddc.vim'
depends  = ['denops.vim']
on_event = 'InsertEnter'
hook_add = 'call deinhook#ddc#hookadd()'

[[plugins]]
repo    = 'Shougo/ddc-around'
depends = 'ddc.vim'

[[plugins]]
repo    = 'Shougo/ddc-converter_remove_overlap'
depends = 'ddc.vim'

[[plugins]]
repo    = 'Shougo/ddc-matcher_head'
depends = 'ddc.vim'

[[plugins]]
repo    = 'Shougo/ddc-nextword'
depends = 'ddc.vim'

[[plugins]]
repo    = 'Shougo/ddc-nvim-lsp'
depends = 'ddc.vim'

[[plugins]]
repo    = 'Shougo/ddc-sorter_rank'
depends = 'ddc.vim'
# }}}

# LSP関連 {{{
[[plugins]]
repo        = 'neovim/nvim-lspconfig'
on_event    = 'BufEnter'
hook_source = '''
lua << EOF
require'lspconfig'.pyright.setup{}
EOF
'''
# }}}
