# プラグインの削除はTOMLファイルからエントリを削除後,以下のコマンドを實行する
# call map(dein#check_clean(), "delete(v:val, 'rf')")
# call dein#recache_runtimepath()

# MatchTagAlways {{{
# https://github.com/Valloric/MatchTagAlways
# 対応するタグをハイライトする
[[plugins]]
repo  = 'Valloric/MatchTagAlways'
on_ft = ['html', 'jinja', 'xhtml', 'xml']
# }}}

# agit.vim {{{
[[plugins]]
repo   = 'cohama/agit.vim'
on_cmd = ['Agit', 'AgitFile']
# }}}

# dein.vim {{{
[[plugins]]
repo = 'Shougo/dein.vim'
# }}}

[[plugins]]
repo             = 'Shougo/vimproc'
host_post_update = 'call deinhook#vimproc#hookpostupdate()'

# vim-toml {{{
[[plugins]]
repo = 'cespare/vim-toml'
# }}}

#[[plugins]]
#repo        = 'gcmt/wildfire.vim'
#hook_source = 'call deinhook#wildfire#hookadd()'

# vim:set fileencoding=utf-8 fileformat=unix foldmethod=marker:
