# プラグインの削除はTOMLファイルからエントリを削除後,以下のコマンドを實行する
# call map(dein#check_clean(), "delete(v:val, 'rf')")
# call dein#recache_runtimepath()

[[plugins]]
repo             = 'Shougo/vimproc'
host_post_update = 'call deinhook#vimproc#hookpostupdate()'

# vim:set fileencoding=utf-8 fileformat=unix foldmethod=marker:
