# プラグインの削除はTOMLファイルからエントリを削除後,以下のコマンドを實行する
# call map(dein#check_clean(), "delete(v:val, 'rf')")
# call dein#recache_runtimepath()

# MatchTagAlways {{{
# https://github.com/Valloric/MatchTagAlways
# 対応するタグをハイライトする
[[plugins]]
repo  = 'Valloric/MatchTagAlways'
on_ft = ['html', 'jinja', 'xhtml', 'xml']
# }}}

# agit.vim {{{
[[plugins]]
repo   = 'cohama/agit.vim'
on_cmd = ['Agit', 'AgitFile']
# }}}

# ddu.vim {{{
# https://github.com/Shougo/ddu.vim
[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo = 'Shougo/ddu-kind-file'

[[plugins]]
repo = 'Shougo/ddu-kind-word'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'

[[plugins]]
repo = 'Shougo/ddu-source-line'

[[plugins]]
repo = 'kuuote/ddu-source-mr'

[[plugins]]
repo = 'Shougo/ddu-source-register'

[[plugins]]
repo = 'shun/ddu-source-rg'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'

[[plugins]]
repo = 'lambdalisue/mr.vim'

[[plugins]]
repo     = 'Shougo/ddu.vim'
hook_add = 'call deinhook#ddu#hookadd()'
# }}}

# dein.vim {{{
[[plugins]]
repo = 'Shougo/dein.vim'
# }}}

[[plugins]]
repo     = 'itchyny/lightline.vim'
hook_add = 'call deinhook#lightline#hookadd()'

[[plugins]]
repo     = 'osyo-manga/vim-anzu'
on_map   = ['<Plug>(anzu-']
hook_add = 'call deinhook#vim_anzu#hookadd()'

[[plugins]]
repo        = 'junegunn/vim-easy-align'
on_map      = ['gb']
hook_source = 'call deinhook#vim_easy_align#hookadd()'

# vim-fugitive {{{
# https://github.com/lambdalisue/vim-gista
[[plugins]]
repo             = 'tpope/vim-fugitive'
on_cmd           = ['Gdiffsplit', 'Git', 'Git!', 'Gwrite', 'Gvdiffsplit']
on_func          = ['fugitive#head']
hook_post_source = '''
    " http://lambdalisue.hatenablog.com/entry/2014/07/01/203015
    doautoall fugitive BufNewFile
'''
# }}}

[[plugins]]
repo        = 'lambdalisue/vim-gista'
on_cmd      = ['Gista']
pre_func    = ['gista#']
hook_source = 'call deinhook#vim_gista#hookadd()'

[[plugins]]
repo             = 'airblade/vim-gitgutter'
lazy             = 1
on_func          = ['GitGutterGetHunkSummary']
hook_add         = 'call deinhook#vim_gitgutter#hookadd()'
hook_post_source = 'call deinhook#vim_gitgutter#hookpostsource()'

[[plugins]]
repo             = 'Shougo/vimproc'
host_post_update = 'call deinhook#vimproc#hookpostupdate()'

# vim-toml {{{
[[plugins]]
repo = 'cespare/vim-toml'
# }}}

#[[plugins]]
#repo        = 'gcmt/wildfire.vim'
#hook_source = 'call deinhook#wildfire#hookadd()'

# vim:set fileencoding=utf-8 fileformat=unix foldmethod=marker:
