# codic-vim
[[plugins]]
repo      = 'koron/codic-vim'
on_cmd    = ['Codic']
on_source = ['unite-codic.vim']

# linediff.vim
[[plugins]]
repo   = 'AndrewRadev/linediff.vim'
on_cmd = ['Linediff', 'LinediffReset']

# neomru
[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# unite-codic.vim
[[plugins]]
repo      = 'rhysd/unite-codic.vim'
depends   = ['codic-vim']
on_source = ['unite.vim']

# unite-mark
[[plugins]]
repo      = 'tacroe/unite-mark'
on_source = ['unite.vim']

# unite-outline
[[plugins]]
repo      = 'Shougo/unite-outline'
on_source = ['unite.vim']

# unite.vim
[[plugins]]
repo    = 'Shougo/unite.vim'
pre_cmd = ['Unite']

# vim-alignta
[[plugins]]
repo   = 'h1mesuke/vim-alignta'
on_cmd = ['Align', 'AlignTsp', 'Alignta']

# vim-fugitive
[[plugins]]
repo    = 'tpope/vim-fugitive'
on_cmd  = ['Gblame', 'Gdiff', 'Gstatus', 'Gwrite', 'Gvdiff']
on_func = ['fugitive#head']

# vim-gitgutter
[[plugins]]
repo    = 'airblade/vim-gitgutter'
on_func = ['GitGutterGetHunkSummary']

# vim-rooter
[[plugins]]
repo   = 'airblade/vim-rooter'
on_cmd = ['Rooter']

# vim-unite-giti
[[plugins]]
repo      = 'kmnk/vim-unite-giti'
on_source = ['unite.vim']
