# dein.vim
[[plugins]]
repo = 'Shougo/dein.vim'

# lightline.vim
[[plugins]]
repo = 'itchyny/lightline.vim'

# vim-colors-solarized
[[plugins]]
repo = 'altercation/vim-colors-solarized'

# vim-localrc
[[plugins]]
repo = 'thinca/vim-localrc'
if   = '!has("win32unix")'

# vim-surround
[[plugins]]
repo = 'tpope/vim-surround'

# wildfire.vim
[[plugins]]
repo = 'gcmt/wildfire.vim'
